# Generated by Django 4.2.5 on 2023-09-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('shortName', models.CharField(default='', max_length=100)),
                ('iconUri', models.URLField()),
                ('manifestUri', models.URLField()),
                ('source', models.CharField(max_length=50)),
                ('focus', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('extraText', models.JSONField()),
                ('certificateUri', models.URLField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, max_length=1024, null=True)),
                ('isFeatured', models.BooleanField(default=False)),
                ('drm', models.JSONField()),
                ('features', models.JSONField()),
                ('licenseServers', models.JSONField()),
                ('licenseRequestHeaders', models.JSONField()),
                ('requestFilter', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('responseFilter', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('clearKeys', models.JSONField()),
                ('extraConfig', models.JSONField(blank=True, default=None, null=True)),
                ('adTagUri', models.URLField(blank=True, default=None, null=True)),
                ('imaVideoId', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('imaAssetKey', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('imaContentSrcId', models.IntegerField(blank=True, default=None, null=True)),
                ('mimeType', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('mediaPlaylistFullMimeType', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('storedProgress', models.IntegerField(default=0)),
                ('storedContent', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
