# Generated by Django 4.2.5 on 2023-09-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('shortName', models.CharField(default='', max_length=100)),
                ('iconUri', models.URLField()),
                ('manifestUri', models.URLField()),
                ('source', models.CharField(max_length=50)),
                ('focus', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('extraText', models.JSONField()),
                ('certificateUri', models.URLField(default=None)),
                ('description', models.TextField(default=None, max_length=1024)),
                ('isFeatured', models.BooleanField(default=False)),
                ('drm', models.JSONField()),
                ('features', models.JSONField()),
                ('licenseServers', models.JSONField()),
                ('licenseRequestHeaders', models.JSONField()),
                ('requestFilter', models.CharField(default=None, max_length=100)),
                ('responseFilter', models.CharField(default=None, max_length=100)),
                ('clearKeys', models.JSONField()),
                ('extraConfig', models.JSONField(default=None)),
                ('adTagUri', models.URLField(default=None)),
                ('imaVideoId', models.IntegerField(default=None)),
                ('imaAssetKey', models.CharField(default=None, max_length=50)),
                ('imaContentSrcId', models.IntegerField(default=None)),
                ('mimeType', models.CharField(default=None, max_length=200)),
                ('mediaPlaylistFullMimeType', models.CharField(default=None, max_length=200)),
                ('storedProgress', models.IntegerField(default=0)),
                ('storedContent', models.JSONField(default=None)),
            ],
        ),
    ]
